config/routes.rb
Rails.application.routes.draw do
  root 	'static_pages#home'
  get 	'/about', 		to:'static_pages#about'
  get 	'/contact', 	to: 'static_pages#contact'
  get 	'/portfolio', 	to: 'static_pages#portfolio'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def portfolio
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_custom_fonts.html.erb
<link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
 <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css"> <!--Make sure you know where these are being used!-->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Put biz logo here. 
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",      about_path %></li>
      <li><%= link_to "Contact",    contact_path %></li>
      <li><%= link_to "Portfolio",  portfolio_path%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
    <div class = "container"> <!--container class provides a responsive fixed width container--><!--container-fluid class full width container spanning entire viewport-->
     <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
       <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %> </li>
        <li><%= link_to "About",  about_path%> </li>
        <li><%= link_to "Portfolio", portfolio_path %></li>
        <li><%= link_to "Log in", '#'%> </li>
       </ul>
      </nav>
     </div>
    </header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> <!--What's this about?-->
 <meta name = "viewport" content="width=device-width, initial-scale=1"> <!--For bootstrap - wasn't in tutorial-->

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><% yield(:title)%></title>
    <%=render 'layouts/rails_default'%>
  	<%=render 'layouts/shim'%>
    <!--Custom Fonts -->
    <%=render 'layouts/custom_fonts'%>
  </head>

  <body>
   <%=render 'layouts/header'%>
      <div class = "container">
      <%=yield%>
      <%=render 'layouts/footer'%>
      </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>
We need a cool form here!  Look at bootstrap freelancer template </p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bitmapped Designs</h1>

  <h2>
   Home Page needs content!
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/portfolio.html.erb
<h1>StaticPages#portfolio</h1>